site_name: Документация Digital Library API
site_description: Руководство по интеграции с ядром цифровой библиотеки

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Перейти на темную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Перейти на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - Введение: index.md
  - Руководство разработчика:
    - Быстрый старт: dev/quickstart.md
    - Описание эндпоинтов API: dev/api_endpoints.md